#!/bin/bash

set -euxo pipefail

sudo apt install devscripts equivs

package="aws-gate"
version="0.11.3"
src_dir="${package}-${version}"

export DEBEMAIL="iain@isme.es"
export DEBFULLNAME="Iain Elder"
dh_make -Ci -y -cbsd

# GitHub's export name just happens to match dh_make's expected directory name.
curl -L "https://github.com/xen0l/${package}/archive/refs/tags/${version}.tar.gz" |
tar -xz

# Make the orig archive.
tar -cJ -f "${package}_${version}.orig.tar.xz" -C "${src_dir}" '.'

cd "$src_dir"
cp -r ../debian .

# Install build dependencies.
sudo mk-build-deps \
    --install \
    --remove \
    --tool='apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes'

export DEBEMAIL="iain@isme.es"
export DEBFULLNAME="Iain Elder"
dh_make -Ci -y -cbsd
